import { useState, type FormEvent } from "react";
import { Flame, TrendingUp } from "lucide-react";
import { Lives } from "../components/Lives";
import { Logo } from "../components/Logo";
import type { Guess, Player, PublicQuestion } from "../types/game";
const labels = { easy: "Fácil", medium: "Médio", hard: "Difícil" };
const format = (n: number) => new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 2 }).format(n);
export function GamePage({ players, question, round, turn, guesses, error, onGuess, onChallenge }: { players: Player[]; question: PublicQuestion; round: number; turn: number; guesses: Guess[]; error: string; onGuess: (n:number)=>void; onChallenge:()=>void }) {
  const last = guesses.at(-1); const [value, setValue] = useState(""); const minimum = last ? last.value : -1;
  function submit(e: FormEvent) { e.preventDefault(); const n = Number(value.replace(",", ".")); if (Number.isFinite(n) && n >= 0 && n > minimum) { onGuess(n); setValue(""); } }
  return <main className="relative z-10 mx-auto min-h-screen max-w-3xl px-4 py-5 sm:py-8"><header className="mb-5 flex items-center justify-between"><Logo small/><span className="rounded-full bg-ink px-4 py-2 text-xs font-black text-white">RODADA {round}</span></header><section className="overflow-hidden rounded-[2rem] border-2 border-ink bg-white shadow-pop"><div className="flex snap-x overflow-x-auto divide-x-2 divide-ink border-b-2 border-ink bg-cream">{players.map(player=><PlayerStatus key={player.id} player={player} active={turn===player.id}/>)}</div><div className="p-5 text-center sm:p-9"><div className="mb-5 flex justify-center gap-2"><span className="rounded-full bg-grape/10 px-4 py-2 text-xs font-black uppercase tracking-wider text-grape">{question.category}</span><span className="rounded-full bg-coral/10 px-4 py-2 text-xs font-black text-coral">{labels[question.difficulty]}</span></div><h1 className="mx-auto max-w-xl text-2xl font-black leading-tight sm:text-4xl">{question.question}</h1><div className="my-7 min-h-28 rounded-3xl bg-ink px-5 py-4 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-white/55">Último palpite</p>{last ? <><p className="mt-1 text-4xl font-black sm:text-5xl">{format(last.value)}</p><p className="mt-1 font-bold text-white/65">{players[last.playerId].name} apostou</p></> : <div className="mt-4 text-xl font-bold text-white/60">Nenhum ainda — abra o jogo!</div>}</div><p className="mb-4 text-lg font-black"><span className="text-grape">{players[turn].name}</span>, é a sua vez</p><form onSubmit={submit}><input autoFocus type="number" inputMode="decimal" min="0" step="any" value={value} onChange={e=>setValue(e.target.value)} placeholder={last ? `Maior que ${format(last.value)}` : "Seu palpite"} className="w-full rounded-2xl border-2 border-ink/20 bg-cream px-4 py-4 text-center text-xl font-black outline-none focus:border-grape focus:ring-4 focus:ring-grape/10 sm:px-5 sm:text-2xl"/><div className="mt-4 grid gap-3 sm:grid-cols-2"><button className="flex items-center justify-center gap-2 rounded-2xl border-2 border-ink bg-lime p-4 font-black shadow-[0_4px_0_#201a38] transition active:translate-y-1 active:shadow-none"><TrendingUp/> {last ? "AUMENTAR" : "DAR PALPITE"}</button><button type="button" disabled={!last} onClick={onChallenge} className="flex items-center justify-center gap-2 rounded-2xl border-2 border-ink bg-coral p-4 font-black text-white shadow-[0_4px_0_#201a38] transition active:translate-y-1 active:shadow-none disabled:cursor-not-allowed disabled:opacity-35"><Flame/> DUVIDO!</button></div></form>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 font-bold text-red-700">{error}</p>}</div></section></main>;
}
function PlayerStatus({ player, active }: { player: Player; active: boolean }) { return <div className={`min-w-32 flex-1 snap-start p-4 text-center transition ${active ? "bg-lime/35" : ""} ${player.lives===0 ? "opacity-40" : ""}`}><p className="truncate font-black">{player.name}</p><div className="mt-1 text-sm"><Lives count={player.lives}/></div></div>; }
