import { useState, type FormEvent } from "react";
import { Logo } from "../components/Logo";
import type { GameSettings } from "../types/game";
const categories = ["Conhecimentos Gerais", "Games", "Filmes e Séries", "Ciência", "História", "Geografia", "Tecnologia", "Esportes", "Misturado", "Personalizado"];
export function HomePage({ onStart }: { onStart: (s: GameSettings) => void }) {
  const [p1, setP1] = useState(""); const [p2, setP2] = useState(""); const [category, setCategory] = useState("Misturado"); const [themes, setThemes] = useState("");
  function submit(e: FormEvent) { e.preventDefault(); if (p1.trim() && p2.trim() && (category !== "Personalizado" || themes.trim())) onStart({ names: [p1.trim(), p2.trim()], category, customThemes: themes.trim() }); }
  const input = "w-full rounded-2xl border-2 border-ink/15 bg-cream/60 px-4 py-3 font-bold outline-none transition focus:border-grape focus:ring-4 focus:ring-grape/10";
  return <main className="relative z-10 mx-auto flex min-h-screen max-w-xl items-center px-4 py-10"><div className="w-full rounded-[2.25rem] border-2 border-ink bg-white p-6 shadow-pop sm:p-10"><div className="text-center"><Logo/><p className="mx-auto mt-3 max-w-sm text-lg font-bold text-ink/60">Um jogo de conhecimento, coragem e palpites questionáveis.</p></div><form onSubmit={submit} className="mt-8 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="font-black">Jogador 1<input className={`${input} mt-1`} value={p1} onChange={e=>setP1(e.target.value)} placeholder="Ex.: Igor" maxLength={24} required/></label><label className="font-black">Jogador 2<input className={`${input} mt-1`} value={p2} onChange={e=>setP2(e.target.value)} placeholder="Ex.: Julia" maxLength={24} required/></label></div><label className="block font-black">Categoria<select className={`${input} mt-1`} value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label>{category === "Personalizado" && <label className="block font-black">Seus temas<textarea className={`${input} mt-1 min-h-24 resize-none`} value={themes} onChange={e=>setThemes(e.target.value)} placeholder="Minecraft, Fórmula 1, Naruto, tecnologia e Brasil" maxLength={240} required/></label>}<button className="mt-2 w-full rounded-2xl border-2 border-ink bg-lime px-6 py-4 text-lg font-black shadow-[0_5px_0_#201a38] transition hover:-translate-y-1 hover:shadow-[0_9px_0_#201a38] active:translate-y-1 active:shadow-none">COMEÇAR PARTIDA →</button></form></div></main>;
}
